name: Build and release pack
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and release pack
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: |
          apt install -y packsquash
          ./gradlew packsquash
      - name: Calculate SHA1
        run: |
          curl -o /usr/local/bin/packsquash https://github.com/ComunidadAylas/PackSquash/releases/download/v0.4.1/packsquash-x86_64-unknown-linux-musl.zip
          chmod +x /usr/local/bin/packsquash
          echo "PACK_SHA1=$(sha1sum build/packsquash/Burb.zip | cut --delimiter " " --fields 1)" >> "$GITHUB_ENV"
      - name: Tag and create release
        uses: softprops/action-gh-release@v2
        with:
          description: "SHA1: ${{ env.PACK_SHA1 }}"
          tag_name: master-v${{ github.run_number }}
          files: build/packsquash/Burb.zip
