name: Build pack
on:
  push:
jobs:
  build:
    name: Build pack
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: |
          curl -Lo packsquash.zip https://github.com/ComunidadAylas/PackSquash/releases/download/v0.4.1/packsquash-x86_64-unknown-linux-gnu.zip
          unzip packsquash.zip -d /usr/local/bin
          chmod +x /usr/local/bin/packsquash
          packsquash -v
          ./gradlew packsquash
      - name: Calculate SHA1
        run: |
          echo "PACK_SHA1=$(sha1sum build/packsquash/Burb.zip | cut --delimiter " " --fields 1)" >> "$GITHUB_ENV"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Burb.zip
          path: build/packsquash/Burb.zip
      - name: Setup MinIO client
        uses: yakubique/setup-minio-cli@v1
      - name: Upload to CDN
        env:
          CDN_S3_URL: ${{ secrets.CDN_S3_URL }}
          CDN_S3_ACCESS_KEY: ${{ secrets.CDN_S3_ACCESS_KEY }}
          CDN_S3_SECRET_KEY: ${{ secrets.CDN_S3_SECRET_KEY }}
        run: |
          mc alias set cdn "$CDN_S3_URL" "$CDN_S3_ACCESS_KEY" "$CDN_S3_SECRET_KEY"
          mc put cdn/resource-packs/burb/packs/${{ env.PACK_SHA1 }}.zip build/packsquash/Burb.zip
          mc pipe cdn/resource-packs/burb/meta/${{ github.ref_name }}.json << EOF
          {
            "packHash": "${{ env.PACK_SHA1 }}",
            "commitId": "${{ github.sha }}"
          }
          EOF